name: Build for Windows

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.6"

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install dependencies
        run: |
          poetry install

      - name: Build
        run: |
          poetry run pyinstaller main.spec

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-executable
          path: dist/main.exe
